### ISSUE TITLE
Fastpath/pipeline: investigate missing Psiphon msmts

### ISSUE THREAD

**Issue by FedericoCeratto** [ooni/backend#296]

**Comment by hellais** [comment]
Was progress done on this during this sprint?

**Comment by hellais** [comment]
Our batch pipeline is not able to access measurements that have names which are not "good names". There were several parts of the batch pipeline codebase which did not behave well when input was missing.

@bassosimone changed the way in which measurements are made in order to ensure they have the requirements.

**Comment by hellais** [comment]
It's unclear what this issue is about, we are closing it due to lack of information.
