### ISSUE TITLE
Investigate now the batch pipeline deals with new Psiphon and Tor experiments

### ISSUE THREAD

**Issue by hellais** [ooni/backend#301]
This involves understanding how the batch pipeline is handling (if it is at all) the ingestion of the new psiphon and tor tests. If there is something we can/should do to support ingesting them.

**Comment by hellais** [comment]
I have started looking into this for the Psiphon test and I have found that a psiphon from a Can:
https://ooni-data.s3.amazonaws.com/canned/2020-01-12/20200112T023855Z-TW-AS1659-psiphon-20200112T023857Z_AS1659_rnewG7VlrvBsM8ZecXwtU4goEYd90YK63YrmHp0xXqaWk7PbD4-0.3.0-probe.json.lz4

end up at the end of the batch pipeline as an empty file:
https://ooni-data.s3.amazonaws.com/autoclaved/jsonl.tar.lz4/2020-01-12/20200112T023855Z-TW-AS1659-psiphon-20200112T023857Z_AS1659_rnewG7VlrvBsM8ZecXwtU4goEYd90YK63YrmHp0xXqaWk7PbD4-0.3.0-probe.json.lz4

This indicates that something is wrong in how the batch pipeline deals with these types of measurements.

I am going to write a test for this and see if we develop a fix for it.

**Comment by bassosimone** [comment]
@hellais can we check again now that we advertise that we're using data format version 0.2.0?

**Comment by hellais** [comment]
We should check these two report files:
```
20200217T100840Z_AS30722_WRpVdRO7ncemc3v4QGtPEWYrhtPt1gpIqytrEnGenNK907wLa0
20200217T100904Z_AS30722_1QkEAEmYKfVbSFuHrf2IcU9qFOwgrBqf1yuMY3MIWI0zw5K1x0
```

But they have been submitted just this morning, so we should check starting from tomorrow once the batch pipeline ticks.

**Comment by bassosimone** [comment]
@hellais I have checked both report files on explorer, and did see the following:

1. https://explorer.ooni.org/measurement/20200217T100840Z_AS30722_WRpVdRO7ncemc3v4QGtPEWYrhtPt1gpIqytrEnGenNK907wLa0

2. https://explorer.ooni.org/measurement/20200217T100904Z_AS30722_1QkEAEmYKfVbSFuHrf2IcU9qFOwgrBqf1yuMY3MIWI0zw5K1x0

I believe it's safe to claim it's the batch pipeline, because the link to download one of the two JSONs is https://api.ooni.io/api/v1/measurement/temp-id-383538180, so it's clearly the legacy pipeline.
