### ISSUE TITLE
Discuss requirements for detecting blocking of OONI services in pipeline

### ISSUE THREAD

**Issue by hellais** [ooni/backend#417]
This is the requirement analysis task for ooni/backend#213

Which is:

> Discover when OONI testing backend infrastructure is being blocked in a particular country or network.

**Comment by bassosimone** [comment]
# Server side blocking measurements

As we discussed in a previous backend meeting, we want to start off by detecting this kind of disruption from the backend side, and only later eventually apply changes in the probe.

As part of such meeting, @hellais also suggested to use different domain names depending on the way in which we submit (e.g. `psiphon`), which is a pretty neat solution.

So, the question now becomes: can we use the system logs to understand what channel is being used for accessing the probe-services by specific users?

(Note: in the following, we're going to shorten report IDs to 32 characters for readability.)

## Case 1: accessing probe services

Here's how a plain measurement submission looks like:

```
1.2.3.4 - - [01/Jan/1970:00:00:00 +0000]
    "POST /report/20200604T111529Z_AS4224_7LW0a9m1 HTTP/1.1" 200 21 "-"
    "miniooni/0.12.0" "ps1.ooni.io"
```

We can use the User-Agent to monitor how updated are the clients. We can use the IP  to know about the country and ASN (or we can use the report ID to just get the ASN).

Knowing the population of users that typically come to a specific service from country/ASN combinations, we can probably infer cases in which a set of users is switching to another probe service because of some kind of disruption (e.g. from `ps1` to `ps2`).

## Case 2: using cloud fronted services

Here's how a measurement submitted using cloud fronted services looks like:

```
1.2.3.4 - - [01/Jan/1970:00:00:00 +0000]
    "POST /report/20200604T111529Z_AS4224_7LW0a9m1 HTTP/1.1" 200 21 "-"
    "Amazon CloudFront" "ps.ooni.io"
```

The IP address is not actionable here because it's the address of the cloud front. We can extract the ASN from the report ID. We don't know which cloud front we are using, because the User Agent header does not tell us that, and the Host header is the one of the box that we are accessing. So, if we want to have more than one cloud front for each probe services box, then we need a way of distinguishing them. This can be done using @hellais's idea of having multiple domain names for different ways of accessing the services.

## Case 3: using a onion service

Here's how a measurement submitted using onion services looks like:

```
127.0.0.1 - - [01/Jan/1970:00:00:00 +0000]
    "POST /report/20200604T111529Z_AS4224_7LW0a9m1 HTTP/1.1" 200 0 "-"
    "-" "jehhrikjjqrlpufu.onion"
```

So, we clearly know it's an onion service because the IP is `127.0.0.1` and we see that the Host header terminates with `.onion`. As for cloud fronted probe services, we can use the ASN inside of the report ID to understand from which networks are users coming from.

(Because this is a legacy way of submitting reports, we probably don't want to spend much time thinking about how we could make them more actionable, tho.)

## Case 3: using Tor as a proxy

Here's how a measurement submitted using `miniooni --proxy=socks5://127.0.0.1:9050` where `127.0.0.1:9050` is a running tor instance looks like:

```
162.247.74.74 - - [01/Jan/1970:00:00:00 +0000]
    "POST /report/20200604T111529Z_AS4224_7LW0a9m1 HTTP/1.1" 200 21 "-"
    "miniooni/0.12.0" "ps.ooni.io"
```

So, here we have `162.247.74.74`, which is the well known address of a Tor exit node. So, we can detect the case where users a proxying through Tor by checking for that.

(This is probably a not-so-common use case, currently. In fact, an external proxy is only supported by `miniooni`, and ooni/probe-legacy uses a onion service.)

## Case 4: fallback to using Tor (or Psiphon)

This is similar to the previous case except that we assume that somehow all the other ways of contacting the probe services fail, and we use Tor/Psiphon. In such case, we can use a specific domain name pointing to the same probe service, as follows:

```
162.247.74.74 - - [01/Jan/1970:00:00:00 +0000]
    "POST /report/20200604T111529Z_AS4224_7LW0a9m1 HTTP/1.1" 200 21 "-"
    "miniooni/0.12.0" "ps-tor.ooni.io"
```
 
It's true that we could probably detect Tor by checking whether the IP is that of an exit node, but maybe having also a specific domain name could be additionally useful.

**Comment by FedericoCeratto** [comment]
Sounds like we can easily implement a tool to classify the logs into 4 groups and create metrics based on that. For a first iteration we can ignore case 3 as it needs lists of exit nodes.

**Comment by bassosimone** [comment]
We clearly discussed this topic and we have a follow-up issue, which is: https://github.com/ooni/backend/issues/428.
