### ISSUE TITLE
cli: test and publish Debian package

### ISSUE THREAD

**Issue by FedericoCeratto** [ooni/backend#452]
Upload a package in Debian contrib/non-free that:
- ask users for permission
- pull and install the probe
- check signatures!
- run weekly checks and install updates automatically. (Stagger checks to do rolling deployments)
- support some EOL flag to disable unsupported hosts permanently?

When asking for updates, send basic info about the host so we can deploy updates only where supported.

Reuse the same update protocol for other OSes?

**Comment by FedericoCeratto** [comment]
https://github.com/ooni/probe-cli/pull/117

**Comment by bassosimone** [comment]
Making good progress. We've just merged https://github.com/ooni/probe-cli/pull/117, which creates the package and publishes it on bintray. Now I am going to add this new package to the e2etesting suite such that it runs every day.

**Comment by bassosimone** [comment]
With https://github.com/ooni/e2etesting/pull/27 merged, we periodically ensure the debian package is WAI.

**Comment by bassosimone** [comment]
We've made good progress with @FedericoCeratto in Sprint 25. There is more work to do in Sprint 26.

**Comment by bassosimone** [comment]
We have further improved the package with @FedericoCeratto here: https://github.com/ooni/probe-cli/pull/162. We now have a package that can be installed and can in the background. The package is triggered by a timer that fires off daily. The user needs to accept data collection while the package is being installed, otherwise there's not running in background.

**Comment by bassosimone** [comment]
I suppose we can call this done! 🎉🎉🎉
