### ISSUE TITLE
Update fastpath to feed from JSONL files

### ISSUE THREAD

**Issue by FedericoCeratto** [ooni/backend#778]
Decompression should be more efficient leading to faster reprocessing and CI runs.

**Comment by hellais** [comment]
ooni/data already uses JSONL files and the fastpath will eventually not need to do any reprocessing (see future of OONI infrastructure).

We should however evaluate if we need to use a more performant file format that isn't JSONL in ooni/data, since JSON parsing is currently the bottlneck there, see: https://github.com/ooni/data/issues/59
